-- DropIndex
DROP INDEX "Pedido_cod_pedido_key";

-- AlterTable
ALTER TABLE "Pedido" ADD COLUMN     "expedicao" TEXT NOT NULL DEFAULT 'F',
ALTER COLUMN "arte" SET DEFAULT 'F',
ALTER COLUMN "arte" SET DATA TYPE TEXT,
ALTER COLUMN "exportacao" SET DEFAULT 'F',
ALTER COLUMN "exportacao" SET DATA TYPE TEXT,
ALTER COLUMN "impressao" SET DEFAULT 'F',
ALTER COLUMN "impressao" SET DATA TYPE TEXT,
ALTER COLUMN "corte" SET DEFAULT 'F',
ALTER COLUMN "corte" SET DATA TYPE TEXT,
ALTER COLUMN "prensa" SET DEFAULT 'F',
ALTER COLUMN "prensa" SET DATA TYPE TEXT,
ALTER COLUMN "costura" SET DEFAULT 'F',
ALTER COLUMN "costura" SET DATA TYPE TEXT;
